=== JereDAM/LNDPROJECT/Ejercicio8/vivero.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="vivero">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="nombre" type="xs:string"></xs:element>
                    <xs:element name="precio">
                       <xs:complexType>
                            <xs:attribute name="moneda" type="xs:integer"></xs:attribute>
                       </xs:complexType>
                    </xs:element>
                <xs:element name="variedad" type="xs:string"></xs:element>
               <xs:element name="origen" type="xs:string"></xs:element>
               <xs:element name="color_fruto" type="xs:string"></xs:element>
               <xs:element name="otros_datos">
                     <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maduracion" type="xs:string"></xs:element>
                            <xs:element name="riesgo" type="xs:string"></xs:element>
                        </xs:sequence>
                     </xs:complexType>
               </xs:element>
            </xs:sequence>
            <xs:attribute name="cantidad" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JereDAM/LNDPROJECT/Ejercicio8/vivero.xml
<?xml version="1.0" encoding="UTF-8"?>
<vivero
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="vivero.xsd"
>
    <especie siembra="2019">
        <nombre>Litchi</nombre>
        <precio moneda="euro">25</precio>
        <variedad>Kway May Pink</variedad>
        <origen>Filipinas</origen>
        <color_fruto>rojo</color_fruto>
        <color_fruto>rosa</color_fruto>
        <otros_datos>
            <maduracion>agosto</maduracion>
            <riesgo>diario</riesgo>
        </otros_datos>
    </especie>
    <especie siembra="2018">
        <nombre>Longan</nombre>
        <precio moneda="euro">10</precio>
        <variedad>Champoo</variedad>
        <origen>China</origen>
        <color_fruto>mar√≥n</color_fruto>
        <otros_datos>
            <maduracion>octubre</maduracion>
            <riesgo>diario</riesgo>
        </otros_datos>
    </especie>  
    <especie siembra="2017">
        <nombre>Litchi</nombre>
        <precio moneda="euro">21</precio>
        <variedad>mauritius</variedad>
        <origen>Florida</origen>
        <color_fruto>rojo</color_fruto>
        <otros_datos>
            <maduracion>agosto</maduracion>
            <riesgo>diario</riesgo>
        </otros_datos>
    </especie>
</vivero>
