<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Socios [
<!ELEMENT socios (persona)+>
<!ATTLIST persona genero CDATA >
<!ATTLIST persona id ID>
<!ELEMENT persona (nombreYapellidos, telefono*, email+, socio)>
<!ELEMENT nombreYapellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT socio (#PCDATA)>
]>

<socios>
    <persona genero="Femenino" id="001">
        <nombreYapellidos>Segundo Pascual</nombreYapellidos>
        <telefono>660777888</telefono>
        <email>user1@gmail.com</email>
        <email>user2@gmail.com</email>
        <email>user3@gmail.com</email>
        <socio>SÃ­</socio>
    </persona>
    <persona genero="Masculino" id="002">
        <nombreYapellidos>Juan Toledo</nombreYapellidos>
        <email>juan@uma.es</email>
        <socio>No</socio>
    </persona>
</socios>
